<h2>Why Organic Delivery?</h2>
<p>Organic foods have always been surrounded by much debate, although increasingly, more and more people are trying to increase their consumption of organic products. To understand why this is the case, we can look back into history and at scientific research to find the rationale behind this popular trend.</p>
<p>The origins of agriculture date back to over 10,000 years ago when hunters and gatherers began to gather seeds and cultivate their favorite crops. As time progressed, each generation of growers added to the knowledge base of food cultivation. Civilizations were built on the foundation of this important knowledge, and the more productive and reliable the food source, the more successful the civilization. Therefore, much emphasis was placed on improving the <strong>&quot;sustainability&quot;</strong> of food production; the ability to produce food successfully and consistently over time.</p>
<p>Moving along the timeline to the 1600s, the knowledge base continued to grow, passed down from generation to generation. Food production had become a refined practice, requiring intricate management, and much had been learned regarding the needs of soil and plants to produce food &quot;sustainably&quot;. Due to limited transportation, food importation was nominal, and most food was sourced from the local area. The land that grew the food needed to do so year after year, eternally... if it failed, the people in that area would suffer. Techniques of rotating crops and animals, cover and green manure cropping, mulching, composting etc. were developed to ensure to long term sustainability of these soils. The focus of many of these important techniques was to incorporate organic matter into the soil, as it improved soil water retention, structure, aeration and fertility: hence the name <strong>&quot;organic farming&quot;</strong>.</p>
<p>The Industrial Revolution a few hundred years later changed the nature of food production immensely. Mechanization permitted the cultivation of larger areas of land, with less need for labor or animal power. These changes started a trend of worker migration from farms to cities. Today only 2% of our population in North America are farmers, a number which is still decreasing. This trend created the need and economic opportunity for agribusiness, the manufacturers of machinery.</p>
<p>As farms became larger (and with the high capital cost of highly specific machinery) farms became specialized at growing only a few crops. In many cases, one type of crop would be grown year after year on the same land without rotation as was done by the forefather farmers. These monoculture farms soon found that over time their soil was no longer fertile and able to provide sustainable yields. The soil structure was also destroyed to the intensive plowing, heavy tractors, and absence of organic matter.</p>
<p>Also, as they were growing only one type of crop, diseases and insect pests became a problem, slowly building up their populations until they were so abundant that they would eliminate an entire harvest. In response to these problems, and coinciding ironically with a huge abundance of chemicals preceding World War 2, pesticides were invented by the same agribusiness companies. The intentions may have been good; however, as time and research has now indicated, these chemicals have been the cause of much pollution and sickness prevalent in today's society.</p>

<p>Many myths surround the viability of organic production.</p>

<ul>
	<li><strong>Can we feed the world without the use of chemical fertilizers and herbicides?</strong> The answer is a definitive yes. Research has shown that there is actually more than enough food produced worldwide to feed our ever increasing population; the problem is the distribution of food: there is an overabundance in some parts, and not enough in others. Also, a study of small organic farms and land use showed that they are up to 50% more efficient and productive than large scale monoculture producers.</li>
	<li><strong>Organic food is too expensive!</strong> Yes, when judged by price, organics are usually more expensive (warning, total plug: except if you compare our produce prices with conventional produce of other stores!). However, prices of conventional food do not consider the so called &quot;externalities&quot; that are not factored into pricing. Externalities are impacts like air, water, and soil pollution from pesticides and herbicides, or human sickness like cancer. Currently we do not calculate these costs in with the price, but who can put a price on clean air or health? Well, some have tried, and after factoring in things like environmental pollution cleanup or cancer research and health care costs, organic food was actually cheaper.</li>
	<li><strong>How can you know that it is organic, really?</strong> By purchasing from certified organic growers. Inspected on a regular basis, these farms must submit management plans that indicate how they intend to maintain soil fertility and crop health without the use of chemical herbicides and pesticides. Inspectors are trained, thirrd party certifying bodies that are independent from the farmer.</li>
	<li><strong>Walmart sells organics; why buy from Localmotive?</strong> Organic food from large superstores is guaranteed to be produced by industrial type monoculture organic farms... yes, there are different degrees of organic! Heathier and more sustainable organic farms are not monocultures; they plant a higher diversity of crops and using less machinery where possible. Hence, &quot;Localmotive&quot;... we are committed to sourcing our foods and products from the Okanagan, then from the greater BC area. We gather our products a day or two prior to your delivery, ensuring that the food is fresh and still packed with nutrients. Pollution from transportation is also reduced, fewer people drive to the store, and less food is imported over long distances. If we import produce, 10% of the sale of that product is used to fund our &quot;Local Food Futures&quot; programme. This program is focused on creating opportunities for increasing the supply of quality local food products, and thereby decreasing imports over time.</li>
</ul>